-- migration: Aggiunge note e esempio ai campi delle categorie HL7 e CONTATTI
-- database: anagrafica

UPDATE extra_data_categorie SET campi = '[{"chiave":"cellulare_1","tipo":"string","obbligatorio":false,"etichetta":"Cellulare principale","note":"Numero di cellulare principale del paziente","esempio":"3331234567"},{"chiave":"cellulare_2","tipo":"string","obbligatorio":false,"etichetta":"Cellulare secondario","note":"Secondo recapito cellulare","esempio":"3409876543"},{"chiave":"email","tipo":"string","obbligatorio":false,"etichetta":"Email","note":"Indirizzo email personale","esempio":"mario.rossi@email.it"},{"chiave":"telefono_fisso","tipo":"string","obbligatorio":false,"etichetta":"Telefono fisso","note":"Recapito telefonico fisso","esempio":"0901234567"},{"chiave":"pec","tipo":"string","obbligatorio":false,"etichetta":"PEC","note":"Posta Elettronica Certificata","esempio":"mario.rossi@pec.it"}]'
WHERE codice = 'CONTATTI';

UPDATE extra_data_categorie SET campi = '[{"chiave":"nome_cognome","tipo":"string","obbligatorio":true,"etichetta":"Nome e Cognome","note":"Nome completo del contatto di emergenza","esempio":"Maria Rossi"},{"chiave":"relazione","tipo":"string","obbligatorio":true,"etichetta":"Relazione","note":"Rapporto con il paziente. Valori: genitore, coniuge, figlio, fratello, altro","esempio":"coniuge"},{"chiave":"telefono","tipo":"string","obbligatorio":true,"etichetta":"Telefono","note":"Recapito telefonico del contatto","esempio":"3331234567"},{"chiave":"note","tipo":"string","obbligatorio":false,"etichetta":"Note","note":"Informazioni aggiuntive sul contatto","esempio":"Disponibile solo dopo le 18"}]'
WHERE codice = 'HL7_CONTATTI_EMERGENZA';

UPDATE extra_data_categorie SET campi = '[{"chiave":"lista","tipo":"json","obbligatorio":false,"etichetta":"Lista allergie","note":"Array di oggetti allergia. Campi: sostanza (obb.), tipo (allergy/intolerance), categoria (food/medication/environment/biologic), criticita (low/high/unable-to-assess), reazione, severita (mild/moderate/severe), data_insorgenza (YYYY-MM-DD), stato (active/inactive/resolved), note","esempio":"Vedi schema sotto-campi"}]'
WHERE codice = 'HL7_ALLERGIE';

UPDATE extra_data_categorie SET campi = '[{"chiave":"lista","tipo":"json","obbligatorio":false,"etichetta":"Lista patologie croniche","note":"Array di oggetti patologia. Campi: codice_icd9, codice_icd10, descrizione (obb.), stato_clinico (obb. active/recurrence/relapse/inactive/remission/resolved), data_insorgenza, data_risoluzione, severita (mild/moderate/severe), note","esempio":"Vedi schema sotto-campi"}]'
WHERE codice = 'HL7_PATOLOGIE_CRONICHE';

UPDATE extra_data_categorie SET campi = '[{"chiave":"lista","tipo":"json","obbligatorio":false,"etichetta":"Lista esenzioni","note":"Array di oggetti esenzione SSN. Campi: codice_esenzione (obb. es. 013.250), descrizione, tipo (obb. patologia/reddito/invalidita/gravidanza/eta), data_inizio (obb. YYYY-MM-DD), data_fine, asl_rilascio","esempio":"Vedi schema sotto-campi"}]'
WHERE codice = 'HL7_ESENZIONI';

UPDATE extra_data_categorie SET campi = '[{"chiave":"lista","tipo":"json","obbligatorio":false,"etichetta":"Lista terapie croniche","note":"Array di oggetti terapia. Campi: farmaco (obb.), codice_aic, dosaggio, frequenza, via_somministrazione (orale/im/ev/sc/topica/inalatoria/sublinguale/rettale/transdermica), data_inizio, prescrittore, note","esempio":"Vedi schema sotto-campi"}]'
WHERE codice = 'HL7_TERAPIE_CRONICHE';

UPDATE extra_data_categorie SET campi = '[{"chiave":"pressione_sistolica","tipo":"number","obbligatorio":false,"etichetta":"Pressione Sistolica (mmHg)","note":"LOINC 8480-6","esempio":"130"},{"chiave":"pressione_diastolica","tipo":"number","obbligatorio":false,"etichetta":"Pressione Diastolica (mmHg)","note":"LOINC 8462-4","esempio":"85"},{"chiave":"frequenza_cardiaca","tipo":"number","obbligatorio":false,"etichetta":"Frequenza Cardiaca (bpm)","note":"LOINC 8867-4","esempio":"72"},{"chiave":"peso_kg","tipo":"number","obbligatorio":false,"etichetta":"Peso (kg)","note":"LOINC 29463-7","esempio":"78.5"},{"chiave":"altezza_cm","tipo":"number","obbligatorio":false,"etichetta":"Altezza (cm)","note":"LOINC 8302-2","esempio":"175"},{"chiave":"bmi","tipo":"number","obbligatorio":false,"etichetta":"BMI","note":"LOINC 39156-5 - peso/(altezza_m^2)","esempio":"25.6"},{"chiave":"glicemia","tipo":"number","obbligatorio":false,"etichetta":"Glicemia (mg/dL)","note":"LOINC 2339-0 - a digiuno","esempio":"110"},{"chiave":"saturazione_o2","tipo":"number","obbligatorio":false,"etichetta":"Saturazione O2 (%)","note":"LOINC 2708-6 - SpO2","esempio":"98"},{"chiave":"temperatura","tipo":"number","obbligatorio":false,"etichetta":"Temperatura (C)","note":"LOINC 8310-5","esempio":"36.5"},{"chiave":"data_rilevazione","tipo":"date","obbligatorio":false,"etichetta":"Data Rilevazione","note":"Data della rilevazione dei parametri","esempio":"2025-03-20"},{"chiave":"note","tipo":"string","obbligatorio":false,"etichetta":"Note","note":"Osservazioni sulla rilevazione","esempio":"Post-prandiale"}]'
WHERE codice = 'HL7_PARAMETRI_VITALI';

UPDATE extra_data_categorie SET campi = '[{"chiave":"lista","tipo":"json","obbligatorio":false,"etichetta":"Lista consensi","note":"Array di oggetti consenso. Campi: tipo_consenso (obb. trattamento_dati/fse/telemedicina/ricerca/vaccinazioni), stato (obb. active/rejected/inactive), data_rilascio (obb. YYYY-MM-DD), data_revoca, modalita (cartaceo/digitale/spid), note","esempio":"Vedi schema sotto-campi"}]'
WHERE codice = 'HL7_CONSENSI';
