-- migration: Aggiunge schema di validazione ai campi JSON delle categorie HL7
-- database: anagrafica

UPDATE extra_data_categorie SET campi = '[{"chiave":"lista","tipo":"json","obbligatorio":false,"etichetta":"Lista allergie","note":"Array di oggetti allergia con schema validato","esempio":"Vedi schema sotto-campi","schema":[{"chiave":"sostanza","tipo":"string","obbligatorio":true,"etichetta":"Sostanza"},{"chiave":"tipo","tipo":"enum","obbligatorio":true,"etichetta":"Tipo","valori":["allergy","intolerance"]},{"chiave":"categoria","tipo":"enum","obbligatorio":false,"etichetta":"Categoria","valori":["food","medication","environment","biologic"]},{"chiave":"criticita","tipo":"enum","obbligatorio":true,"etichetta":"Criticita","valori":["low","high","unable-to-assess"]},{"chiave":"reazione","tipo":"string","obbligatorio":false,"etichetta":"Reazione"},{"chiave":"severita","tipo":"enum","obbligatorio":false,"etichetta":"Severita","valori":["mild","moderate","severe"]},{"chiave":"data_insorgenza","tipo":"date","obbligatorio":false,"etichetta":"Data insorgenza"},{"chiave":"stato","tipo":"enum","obbligatorio":false,"etichetta":"Stato","valori":["active","inactive","resolved"]},{"chiave":"note","tipo":"string","obbligatorio":false,"etichetta":"Note"}]}]'
WHERE codice = 'HL7_ALLERGIE';

UPDATE extra_data_categorie SET campi = '[{"chiave":"lista","tipo":"json","obbligatorio":false,"etichetta":"Lista patologie croniche","note":"Array di oggetti patologia con schema validato","esempio":"Vedi schema sotto-campi","schema":[{"chiave":"codice_icd9","tipo":"string","obbligatorio":false,"etichetta":"Codice ICD-9"},{"chiave":"codice_icd10","tipo":"string","obbligatorio":false,"etichetta":"Codice ICD-10"},{"chiave":"descrizione","tipo":"string","obbligatorio":true,"etichetta":"Descrizione"},{"chiave":"stato_clinico","tipo":"enum","obbligatorio":true,"etichetta":"Stato clinico","valori":["active","recurrence","relapse","inactive","remission","resolved"]},{"chiave":"data_insorgenza","tipo":"date","obbligatorio":false,"etichetta":"Data insorgenza"},{"chiave":"data_risoluzione","tipo":"date","obbligatorio":false,"etichetta":"Data risoluzione"},{"chiave":"severita","tipo":"enum","obbligatorio":false,"etichetta":"Severita","valori":["mild","moderate","severe"]},{"chiave":"note","tipo":"string","obbligatorio":false,"etichetta":"Note"}]}]'
WHERE codice = 'HL7_PATOLOGIE_CRONICHE';

UPDATE extra_data_categorie SET campi = '[{"chiave":"lista","tipo":"json","obbligatorio":false,"etichetta":"Lista esenzioni","note":"Array di oggetti esenzione SSN con schema validato","esempio":"Vedi schema sotto-campi","schema":[{"chiave":"codice_esenzione","tipo":"string","obbligatorio":true,"etichetta":"Codice esenzione"},{"chiave":"descrizione","tipo":"string","obbligatorio":false,"etichetta":"Descrizione"},{"chiave":"tipo","tipo":"enum","obbligatorio":true,"etichetta":"Tipo","valori":["patologia","reddito","invalidita","gravidanza","eta"]},{"chiave":"data_inizio","tipo":"date","obbligatorio":true,"etichetta":"Data inizio"},{"chiave":"data_fine","tipo":"date","obbligatorio":false,"etichetta":"Data fine"},{"chiave":"asl_rilascio","tipo":"string","obbligatorio":false,"etichetta":"ASL rilascio"}]}]'
WHERE codice = 'HL7_ESENZIONI';

UPDATE extra_data_categorie SET campi = '[{"chiave":"lista","tipo":"json","obbligatorio":false,"etichetta":"Lista terapie croniche","note":"Array di oggetti terapia con schema validato","esempio":"Vedi schema sotto-campi","schema":[{"chiave":"farmaco","tipo":"string","obbligatorio":true,"etichetta":"Farmaco"},{"chiave":"codice_aic","tipo":"string","obbligatorio":false,"etichetta":"Codice AIC"},{"chiave":"dosaggio","tipo":"string","obbligatorio":false,"etichetta":"Dosaggio"},{"chiave":"frequenza","tipo":"string","obbligatorio":false,"etichetta":"Frequenza"},{"chiave":"via_somministrazione","tipo":"enum","obbligatorio":false,"etichetta":"Via somministrazione","valori":["orale","im","ev","sc","topica","inalatoria","sublinguale","rettale","transdermica"]},{"chiave":"data_inizio","tipo":"date","obbligatorio":false,"etichetta":"Data inizio"},{"chiave":"prescrittore","tipo":"string","obbligatorio":false,"etichetta":"Prescrittore"},{"chiave":"note","tipo":"string","obbligatorio":false,"etichetta":"Note"}]}]'
WHERE codice = 'HL7_TERAPIE_CRONICHE';

UPDATE extra_data_categorie SET campi = '[{"chiave":"lista","tipo":"json","obbligatorio":false,"etichetta":"Lista consensi","note":"Array di oggetti consenso con schema validato","esempio":"Vedi schema sotto-campi","schema":[{"chiave":"tipo_consenso","tipo":"enum","obbligatorio":true,"etichetta":"Tipo consenso","valori":["trattamento_dati","fse","telemedicina","ricerca","vaccinazioni"]},{"chiave":"stato","tipo":"enum","obbligatorio":true,"etichetta":"Stato","valori":["active","rejected","inactive"]},{"chiave":"data_rilascio","tipo":"date","obbligatorio":true,"etichetta":"Data rilascio"},{"chiave":"data_revoca","tipo":"date","obbligatorio":false,"etichetta":"Data revoca"},{"chiave":"modalita","tipo":"enum","obbligatorio":false,"etichetta":"Modalita","valori":["cartaceo","digitale","spid"]},{"chiave":"note","tipo":"string","obbligatorio":false,"etichetta":"Note"}]}]'
WHERE codice = 'HL7_CONSENSI';
